### ISSUE TITLE
Erro em Cadastro de Titulos

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#2]
Ao tentar realizar o cadastro de um novo título para cliente, o resultado da requisição é 200, porém não é adicionado no DB. Vale lembrar que estou utilizando um cliente recém criado. V: 2.2.0;
 A seguir, o body da Requisição:
`{
"users_id":8,
"debtor_id":8,
"emission_date":"2023-02-28T20:55:26.260Z",
"due_date":"2023-03-30T20:55:26.260Z",
"amount":15000,
"status":"Open",
"description":"Nenhuma por enquanto",
}`

![image](https://user-images.githubusercontent.com/88745612/221582200-b086768e-8953-4b53-9762-f42ef8431683.png)

**Comment by themegazord** [comment]
Segundo a documentação, tanto o campo `emission_date` quanto o campo `due_date` são do tipo `string` como você está passando, porém, deve ser passado apenas a data separado por `-` no seguinte _label_, `YYYY-mm-dd`, como mostra o exemplo tirado da documentação.

```json
{
    "users_id": 5,
    "debtor_id": 5,
    "emission_date": "2022-12-29",
    "due_date": "2023-02-03",
    "amount": 94.96,
    "status": "Open",
    "description": "teste"
}
```

Contudo a validação existente no sistema deveria ter bloqueado esse tipo de dado inválido e será tratado na próxima versão.

**Comment by themegazord** [comment]
Não será gerado nova versão pois o sistema já valida isso

![image](https://user-images.githubusercontent.com/75401705/221611965-faa80f42-af28-4c3c-9b51-0470f3f61084.png)
