### ISSUE TITLE
Valores de Requisição incompletos

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#3]
**Descrição**
Na rota de clientes (inadimplentes ou adimplentes), é esperado que tenha o id do cliente;

Versão 2.2.0

![image](https://user-images.githubusercontent.com/88745612/221619630-e5aef88a-8916-44e4-84a6-eea71d4f5ff8.png);

**Comment by themegazord** [comment]
Os endpoint's de clientes inadimplentes e adimplentes são da mesma rota da consulta de clientes.

Inadimplementes = `GET /api/debtors/defaulters/user/{id}`
Adimplentes = `GET /api/debtors/payers/user/{id}`
Consulta de Clientes = ` GET /api/debtors/user/{id}`

Por sua vez, a chave `id` é a chave do cliente.
