### ISSUE TITLE
Resposta de Requisição incompleta

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#4]
**Descrição**

Chave "status" no endpoint "/api/debtors/user/{id}" faltando;

**Comment by IndioBR** [comment]
![image](https://user-images.githubusercontent.com/88745612/221691160-a4e8f4e1-3b0b-4758-b6b7-f58e29d7a037.png)

**Comment by themegazord** [comment]
Inclusão realizada na versão 2.2.1

O retorno do campo agora será:

```json
{
        "status": "Defaulter",
        "id": 8,
        "user_id": 8,
        "name": "Gustavo de Camargo Campos",
        "email": "contato.wanjalagus@outlook.com.br",
        "cpf": "05081039160",
        "phone": "67981590619",
        "address": null,
        "complement": null,
        "cep": null,
        "neighborhood": null,
        "city": null,
        "state": null,
        "created_at": "2023-02-23T19:29:07.000000Z",
        "updated_at": "2023-02-23T19:29:07.000000Z"
    }
```

Para maiores detalhes, verificar a doc do endpoint, [clicando aqui](https://github.com/themegazord/backend-project-cubos/blob/main/doc/debtors/users-debtors.md)
