### ISSUE TITLE
erro em: Atualização de usuário

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#5]
Descrição:
 - No front, passando o objeto na requisição com as chaves corretas, a resposta informa que os campos obrigatórios não estão preenchidos. Porém, como está na imagem [1], as chaves foram preenchidas.
 - Na imagem [2] está a função que usei com fetch api para a requisição.

Imagem 1:

![image](https://user-images.githubusercontent.com/88745612/222761167-c8bef1ed-839d-448c-b5bd-eee4351fc032.png)

Imagem 2:

![image](https://user-images.githubusercontent.com/88745612/222761312-68c60958-7c37-42c6-9950-770b683e588f.png)

**Comment by themegazord** [comment]
Me manda o JSON que você está enviando para o backend por favor.

**Comment by IndioBR** [comment]
{
      name: "Jonatas",
      email: "email@email.com",
      password: "password",
      cpf: "",
      phone: "",
    }

**Comment by themegazord** [comment]
Atualizado para aceitar o campo em vazio `""` ou `null`.

Basta fazer `git pull`.

Bom código 😄
