### ISSUE TITLE
Documentação incompleta. 

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#6]
**Describe the bug**
Faltando alguns campos na rota de cadastro de cliente. Espero enviar [Endereço, Complemento, CEP, Bairro]

**Screenshots**
![image](https://user-images.githubusercontent.com/88745612/225623638-63be2fa9-0ac2-46ae-a1b5-7b8a62d39842.png)

**Comment by themegazord** [comment]
Realizado a correção da documentação nos arquivos destinados a inserção e atualização de clientes.

Versão atual da documentação: `0.0.4`
