### ISSUE TITLE
Erro em Listagem de Clientes

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#7]
**Describe the bug**
Listagem de clientes não retorna todos os clientes cadastrados.

**Screenshots**
![image](https://user-images.githubusercontent.com/88745612/225644008-fcc838a4-f4bb-4778-bbe4-f9fe48295201.png)
![image](https://user-images.githubusercontent.com/88745612/225644092-791dc1e6-2c77-4dd6-a9f4-8b427c42c8ca.png)

**Comment by themegazord** [comment]
Realizado correção.

Agora, todas os clientes novos vão ficar com o status `New`, a partir do momento que for criado um titulo para este cliente, ele assumirá o status de `Payer` ou `Defaulter`
