### ISSUE TITLE
404 na rota /api/installments/{id}

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#8]
**Describe the bug**
Erro 404 na rota de edição de títulos. Versão 2.2.1

**Expected behavior**
Um status 200.

**Req**
{
    "users_id": 8,
    "debtor_id": 8,
    "id_billing": "5958088f-2bb2-42ce-b7d7-7faa9d2b0300",
    "emission_date": "2023-03-17",
    "description": "Nenhuma por enquanto",
    "due_date": "2023-03-30",
    "amount": "15000",
    "status": "paid",
    "_method": "PATCH"
}

**Comment by themegazord** [comment]
Corrigido na nova versão.

Favor, olhar a documentação de titulos.

Branch que foi reparada: fix/https://github.com/themegazord/backend-project-cubos/issues/8/reparo-na-rotina-installments
Commit: https://github.com/themegazord/backend-project-cubos/commit/f8b39eba1ff44118c8a964fc2d0c4e53bffd3f59
