### ISSUE TITLE
500 na rota /api/installments?filter=users_id:=:{id}

### ISSUE THREAD

**Issue by IndioBR** [themegazord/backend-project-cubos#9]
**Describe the bug**
Depois de adicionar um título novo, ao fazer a requisição na GET /api/installments?filter=users_id:=:{id}, a resposta deveria ser uma lista atualizada dos títulos, mas recebo um 500.

**Expected behavior**
A lista atualizada de títulos.

**Response**
"App\\Services\\Installment\\InstallmentService::determineStatusInstallment(): Return value must be of type array, none returned"
trace

**Comment by themegazord** [comment]
Corrigido na nova versão.

Favor, olhar a documentação de titulos.

Branch que foi reparada: fix/#8/reparo-na-rotina-installments
Commit: https://github.com/themegazord/backend-project-cubos/commit/f8b39eba1ff44118c8a964fc2d0c4e53bffd3f59
